### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by emmakamau94**
Code review @sgatana

### CODE REVIEW

**Comment by sgatana** [comment]
Hey @emmakamau94 

This looks very good! Shows a very good understanding of the use of object classes in python. I believe you will defend your code well to show this understanding.

I Love the code organization and the commit messages. Good stuff.

Good luck!

**Comment by sgatana** [comment]
The code in items.html  looks okay to me but try to use an external css file

**Comment by emmakamau94** [comment]
The PR creates functionality for the shopping list application.
Tasks to be completed include:   
      1. Actualize CRUD
      2. Enable user to create an account
      3. Enable user to create a shopping list
      4. Write tests

**Comment by steveMuema** [comment]
Good progress. work on now adding more tests and css on html as commented by sgatana.

**Pull request merged**
